//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyS___DeportesConcepcioin_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ant_personales
    {
        public int id_ant_per { get; set; }
        public string enferme_infancia { get; set; }
        public string alergias { get; set; }
        public string operaciones { get; set; }
        public string traumatismos { get; set; }
        public string alteracion_visual { get; set; }
        public Nullable<double> talla { get; set; }
        public Nullable<double> peso { get; set; }
        public Nullable<double> fc { get; set; }
        public Nullable<double> pa { get; set; }
        public string alteracion_postural { get; set; }
        public string genu_valgo_varu { get; set; }
        public string pie_plano_valgo { get; set; }
        public string otro { get; set; }
        public int futbolista_id_futbolista { get; set; }
    
        public virtual futbolista futbolista { get; set; }
    }
}
