//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyS___DeportesConcepcioin_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comentario_nutri
    {
        public int id_coment { get; set; }
        public string descripción_com { get; set; }
        public System.DateTime fecha_coment { get; set; }
        public int futbolista_id_futbolista { get; set; }
    
        public virtual futbolista futbolista { get; set; }
    }
}
