//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyS___DeportesConcepcioin_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuerpo_tec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cuerpo_tec()
        {
            this.entrenamiento = new HashSet<entrenamiento>();
        }
    
        public int id_cu_tec { get; set; }
        public string nom_ct { get; set; }
        public string appaterno_ct { get; set; }
        public string apmaterno_ct { get; set; }
        public string email_ct { get; set; }
        public int telefono_ct { get; set; }
        public string estado_ct { get; set; }
        public byte[] foto_perfil { get; set; }
        public string usuario_rut_usuario { get; set; }
    
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<entrenamiento> entrenamiento { get; set; }
    }
}
