//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyS___DeportesConcepcioin_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class encuesta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public encuesta()
        {
            this.pregunta = new HashSet<pregunta>();
            this.respuesta = new HashSet<respuesta>();
        }
    
        public int id_encuesta { get; set; }
        public string descripcion_encuesta { get; set; }
        public System.DateTime fecha_encuesta { get; set; }
        public System.DateTime fecha_limite_encuesta { get; set; }
        public string estado_encuesta { get; set; }
        public Nullable<int> nutricionista_id_nutri { get; set; }
        public Nullable<int> kinesiologo_id_kinesiologo { get; set; }
    
        public virtual kinesiologo kinesiologo { get; set; }
        public virtual nutricionista nutricionista { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pregunta> pregunta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<respuesta> respuesta { get; set; }
    }
}
