//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyS___DeportesConcepcioin_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class entrenamiento
    {
        public int id_entrenamiento { get; set; }
        public System.DateTime fecha_entr { get; set; }
        public int volumen_entr { get; set; }
        public string objetivo_entr { get; set; }
        public string comentario { get; set; }
        public int cuerpo_tec_id_cu_tec { get; set; }
        public int categoria_id_categoria { get; set; }
        public int tipo_entrenam_id_tipo_entr { get; set; }
    
        public virtual categoria categoria { get; set; }
        public virtual cuerpo_tec cuerpo_tec { get; set; }
        public virtual tipo_entrenam tipo_entrenam { get; set; }
    }
}
