//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyS___DeportesConcepcioin_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hist_clinico
    {
        public int id_historial_clinico { get; set; }
        public System.DateTime fecha_lesion { get; set; }
        public string lugar_lesion { get; set; }
        public string zona_lesion { get; set; }
        public string relacion_lesion_anterior { get; set; }
        public System.DateTime fecha_baja { get; set; }
        public int dias_baja { get; set; }
        public string examenes { get; set; }
        public string tratamiento { get; set; }
        public string observacion { get; set; }
        public int futbolista_id_futbolista { get; set; }
        public int lesion_id_lesion { get; set; }
    
        public virtual futbolista futbolista { get; set; }
        public virtual lesion lesion { get; set; }
    }
}
