//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyS___DeportesConcepcioin_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class insumo
    {
        public int id_insumo { get; set; }
        public string descripcion_insumo { get; set; }
        public string tipo_insumo { get; set; }
        public int cantidad_insumo { get; set; }
        public string comentarioinsumo { get; set; }
        public System.DateTime fecha_insumo { get; set; }
        public string estado_insumo { get; set; }
        public int futbolista_id_futbolista { get; set; }
        public Nullable<int> kinesiologo_id_kinesiologo { get; set; }
    
        public virtual futbolista futbolista { get; set; }
        public virtual kinesiologo kinesiologo { get; set; }
    }
}
