//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyS___DeportesConcepcioin_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kinesiologo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kinesiologo()
        {
            this.encuesta = new HashSet<encuesta>();
            this.insumo = new HashSet<insumo>();
        }
    
        public int id_kinesiologo { get; set; }
        public string nom_kinesiologo { get; set; }
        public string appaterno_kine { get; set; }
        public string apmaterno_kine { get; set; }
        public string email_kine { get; set; }
        public int telefono_kine { get; set; }
        public string estado_kinesiologo { get; set; }
        public string usuario_rut_usuario { get; set; }
        public byte[] foto_perfil { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<encuesta> encuesta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<insumo> insumo { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
