//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyS___DeportesConcepcioin_v2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ant_familiar> ant_familiar { get; set; }
        public virtual DbSet<ant_personales> ant_personales { get; set; }
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<comentario_nutri> comentario_nutri { get; set; }
        public virtual DbSet<cuerpo_tec> cuerpo_tec { get; set; }
        public virtual DbSet<encuesta> encuesta { get; set; }
        public virtual DbSet<entrenamiento> entrenamiento { get; set; }
        public virtual DbSet<ev_nutri> ev_nutri { get; set; }
        public virtual DbSet<futbolista> futbolista { get; set; }
        public virtual DbSet<hist_clinico> hist_clinico { get; set; }
        public virtual DbSet<insumo> insumo { get; set; }
        public virtual DbSet<kinesiologo> kinesiologo { get; set; }
        public virtual DbSet<lesion> lesion { get; set; }
        public virtual DbSet<nutricionista> nutricionista { get; set; }
        public virtual DbSet<pregunta> pregunta { get; set; }
        public virtual DbSet<respuesta> respuesta { get; set; }
        public virtual DbSet<suplemento> suplemento { get; set; }
        public virtual DbSet<tipo_entrenam> tipo_entrenam { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
