//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyS___DeportesConcepcioin_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pregunta
    {
        public int id_pregunta { get; set; }
        public string descripcion_pregunta { get; set; }
        public Nullable<System.DateTime> fecha_pregunta { get; set; }
        public byte[] imagenpregunta { get; set; }
        public int encuesta_id_encuesta { get; set; }
    
        public virtual encuesta encuesta { get; set; }
    }
}
