//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyS___DeportesConcepcioin_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class respuesta
    {
        public int id_respuesta { get; set; }
        public string descripcion_respuesta { get; set; }
        public System.DateTime fecha_respuesta { get; set; }
        public int encuesta_id_encuesta { get; set; }
        public int futbolista_id_futbolista { get; set; }
    
        public virtual encuesta encuesta { get; set; }
        public virtual futbolista futbolista { get; set; }
    }
}
