//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CyS___DeportesConcepcioin_v2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class suplemento
    {
        public int id_suplemento { get; set; }
        public string desc_suplemento { get; set; }
        public string tipo_suplemento { get; set; }
        public int cant_suplemento { get; set; }
        public System.DateTime fecha_suplem { get; set; }
        public string estd_suplemento { get; set; }
        public string comentariosuplem { get; set; }
        public Nullable<int> nutricionista_id_nutri { get; set; }
        public int futbolista_id_futbolista { get; set; }
    
        public virtual futbolista futbolista { get; set; }
        public virtual nutricionista nutricionista { get; set; }
    }
}
